# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict


class RestSleepTime(TypedDict):
    area1: NotRequired[int]
    """
    Remaining time of sleep mode in area 1 in minutes.
    """
    area2: NotRequired[int]
    """
    Remaining time of sleep mode in area 2 in minutes.
    """
    area3: NotRequired[int]
    """
    Remaining time of sleep mode in area 3 in minutes.
    """
    area4: NotRequired[int]
    """
    Remaining time of sleep mode in area 4 in minutes.
    """
    area5: NotRequired[int]
    """
    Remaining time of sleep mode in area 5 in minutes.
    """
    area6: NotRequired[int]
    """
    Remaining time of sleep mode in area 6 in minutes.
    """


class Telemetry(TypedDict):
    restSleepTime: NotRequired[RestSleepTime]
    restFilterTime: NotRequired[int]
    """
    Remaining filter run time in days.
    """
    co2: NotRequired[int]
    """
    Actual sensor value of CO² in ppm.
    """
    humidity: NotRequired[int]
    """
    Actual sensor value of humidity in %.
    """
    Ti: NotRequired[str]
    """
    Actual sensor value of room temperature in °C. (format: CC.C)
    """
    Ta: NotRequired[str]
    """
    Actual sensor value of outside temperature in °C. (format: CC.C)
    """
    uptime: NotRequired[str]
    """
    Uptime of the SEC Smart system. (format: yy.ddd.hh:mm)
    """


class LastMessage(TypedDict):
    """
    A Message containing a time stamp, an error code and a sentence what error was the last on at which time point.
    """

    message: NotRequired[str]
    date: NotRequired[str]
    time: NotRequired[str]


class Notifications(TypedDict):
    filterRanOut: NotRequired[bool]
    """
    Filter time ran out. Filter should be changed and then reset.
    """
    actualMessage: NotRequired[str]
    """
    A Message containing an error code and a sentence what errors exist at this time point.
    """
    lastMessage: NotRequired[LastMessage]
    """
    A Message containing a time stamp, an error code and a sentence what error was the last on at which time point.
    """


class System(TypedDict):
    type: NotRequired[
        Literal[
            'None',
            'SEVi160',
            'SEVi200',
            'SEVi160D Mini Exhaust',
            'SEVi160D Mini',
            'SEVi160 S',
            'SEVi160 Eco',
            'SEVi160 PRO-S',
            'SEVi160 PRO-ECO',
            'SEVi160D Mini PRO Exh.',
            'SEVi160D Mini PRO',
            'Configurable Device',
        ]
    ]
    installed: NotRequired[
        Literal['Area 1', 'Area 2', 'Area 3', 'Area 4', 'Area 5', 'Area 6']
    ]


type BoostMode = Literal[
    'Supply and exhaust air', 'Only supply air', 'Only exhaust air'
]


class Areas1(TypedDict):
    area1: NotRequired[bool]
    area2: NotRequired[bool]
    area3: NotRequired[bool]
    area4: NotRequired[bool]
    area5: NotRequired[bool]
    area6: NotRequired[bool]


class DigitalInput(TypedDict):
    function: NotRequired[
        Literal[
            'None',
            'Set fan stage 0',
            'Set fan stage 1',
            'Set fan stage 2',
            'Set fan stage 3',
            'Set fan stage 4',
            'Set fan stage 5',
            'Set fan stage 6',
            'Set boost ventilation',
            'Set to snooze',
            'Set to automatic timer',
            'Set to CO2',
            'Set to humidity',
            'Reset filter',
            'Keep fan stage 0',
            'Keep fan stage 1',
            'Keep fan stage 2',
            'Keep fan stage 3',
            'Keep fan stage 4',
            'Keep fan stage 5',
            'Keep fan stage 6',
            'Keep boost ventilation',
            'Keep at automatic timer',
            'Keep at CO2',
            'Keep at humidity',
        ]
    ]
    areas: NotRequired[Areas1]


class DigitalOutput(TypedDict):
    function: NotRequired[
        Literal[
            'None',
            'Fan stage 0 active',
            'Fan stage 1 active',
            'Fan stage 2 active',
            'Fan stage 3 active',
            'Fan stage 4 active',
            'Fan stage 5 active',
            'Fan stage 6 active',
            'Boost ventilation active',
            'Snooze mode active',
            'All areas fan stage 0',
            'Automatic timer active',
            'CO2 active',
            'Humidity active',
            'Filter exhausted',
            'General message',
            'General error',
        ]
    ]
    areas: NotRequired[Areas1]


class X(TypedDict):
    lower: NotRequired[int]
    """
    Analog input value in % for the lower setpoint.
    """
    upper: NotRequired[int]
    """
    Analog input value in % for the upper setpoint.
    """


class YFanlevel(TypedDict):
    lower: NotRequired[int]
    """
    Fanlevel to apply at lower setpoint.
    """
    upper: NotRequired[int]
    """
    Fanlevel to apply at upper setpoint.
    """


class YHumidity(TypedDict):
    lower: NotRequired[int]
    """
    Humidity value in % for humidity regulation mode  to apply at lower setpoint.
    """
    upper: NotRequired[int]
    """
    Humidity value in % for humidity regulation mode  to apply at upper setpoint.
    """


class YCO2(TypedDict):
    lower: NotRequired[int]
    """
    CO² value in ppm for CO² regulation mode  to apply at lower setpoint.
    """
    upper: NotRequired[int]
    """
    CO² value in ppm for CO² regulation mode  to apply at upper setpoint.
    """


class YTemp(TypedDict):
    lower: NotRequired[int]
    """
    Lower setpoint in °C for linear curve when used for an analog temperature sensor.
    """
    upper: NotRequired[int]
    """
    Upper setpoint in °C for linear curve when used for an analog temperature sensor.
    """


class CurveParameters(TypedDict):
    x: NotRequired[X]
    yFanlevel: NotRequired[YFanlevel]
    yHumidity: NotRequired[YHumidity]
    yCO2: NotRequired[YCO2]
    yTemp: NotRequired[YTemp]


class AnalogInput(TypedDict):
    function: NotRequired[Literal['None', 'Fan stage', 'Humidity', 'CO2', 'Ti', 'Ta']]
    functionType: NotRequired[Literal['0-10 V', '4-20 mA']]
    areas: NotRequired[Areas1]
    curveParameters: NotRequired[CurveParameters]


class Thresholds(TypedDict):
    humidity: NotRequired[int]
    """
    Threshold for humidity regulation in % relative humidity.
    """
    co2: NotRequired[int]
    """
    Threshold for CO² regulation in ppm. Stepsize is 10.
    """


type Users = list[str]
"""
An array containing all email adresses of users which are connected to this device.
"""


class Controller(TypedDict):
    """
    An object representing a set of data describing your controller hardware configuration.
    """

    articleCode: NotRequired[str]
    """
    Article Code of the Central Control Unit. Please always refer to it if you are reporting issues with your system.
    """
    articleCodeTouchPanel1: NotRequired[str]
    """
    Article Code of the first touch panel. Only shown if connected.
    """
    articleCodeTouchPanel2: NotRequired[str]
    """
    Article Code of the second touch panel. Only shown if connected.
    """
    articleCodeTouchPanel3: NotRequired[str]
    """
    Article Code of the third touch panel. Only shown if connected.
    """


class Gateway(TypedDict):
    """
    An object representing a set of data describing your gateway. Please always report this data when reporting issues.
    """

    articleCode: NotRequired[str]
    """
    Article Code of your gateway.
    """
    id: NotRequired[str]
    """
    6-digit-long alphanumerical ID of the gateway. It is the same as the one of your system.
    """
    firmwareVersion: NotRequired[str]
    """
    The version of the gateway's firmware in the format 'major.minor.fix'.
    """


type DeviceName = str


type AreaMode = Literal[
    'Fans off',
    'Manual 1',
    'Manual 2',
    'Manual 3',
    'Manual 4',
    'Manual 5',
    'Manual 6',
    'Boost ventilation',
    'Humidity regulation',
    'CO2 regulation',
    'Timed program',
    'Snooze',
    'INACTIVE',
]


type AreaLabel = Literal[
    'None',
    'Area 1',
    'Area 2',
    'Area 3',
    'Area 4',
    'Area 5',
    'Area 6',
    'Sitting room',
    'Sitting room 1',
    'Sitting room 2',
    'Dining room',
    'Dining room 1',
    'Dining room 2',
    'Master bedroom',
    'Bedroom 1',
    'Bedroom 2',
    'Childs room',
    'Childs room 1',
    'Childs room 2',
    'Childs room 3',
    'Childs room 4',
    'Kitchen',
    'Kitchen 1',
    'Kitchen 2',
    'Bathroom',
    'Master bathroom',
    'Guest bathroom',
    'WC',
    'Guest WC',
    'Study',
    'Study 1',
    'Study 2',
    'Hobby room',
    'Multi purpose room',
    'Store room',
    'Cellar room',
    'Cellar room 1',
    'Cellar room 2',
    'Cellar room 3',
    'Attic',
    'Attic 1',
    'Attic 2',
    'Attic 3',
    'Office',
    'Office 1',
    'Office 2',
    'Office 3',
    'Office 4',
    'Office 6',
    'Executives office',
    'Department managers office',
    'Purchase dept office',
    'Order Processing office',
    'Development office',
    'Construction office',
    'Accounting office',
    'Dining area',
    'Conference room',
    'Conference room 1',
    'Conference room 2',
    'Conference room 3',
    'Lounge',
    'Library',
    'Fitness room',
    'Winter garden',
    'Craft room',
    'Dressing room',
    'Utility room',
]


type FilterMaxRunTime = int
"""
New maximum filter run time in days.
"""


type SettingsSleepTime = int
"""
Duration of the sleep mode in minutes.
"""


class SettingsDeviceTime(TypedDict):
    """
    Time and Date of your device. If autoSynch is set to true the device will snych automatically with the internet and all manual changes here will be discarded.
    """

    time: NotRequired[str]
    date: NotRequired[str]
    autoSynch: NotRequired[bool]


type SettingsSummerMode = bool
"""
Activation state of the summer ventilation functionality. If active no heat recovery happens.
"""


class SetupSystems(TypedDict):
    system1: NotRequired[System]
    system2: NotRequired[System]
    system3: NotRequired[System]
    system4: NotRequired[System]
    system5: NotRequired[System]
    system6: NotRequired[System]


class SetupAreas(TypedDict):
    area1: NotRequired[BoostMode]
    area2: NotRequired[BoostMode]
    area3: NotRequired[BoostMode]
    area4: NotRequired[BoostMode]
    area5: NotRequired[BoostMode]
    area6: NotRequired[BoostMode]


type SetupInputDi = DigitalInput


type SetupInputAi = AnalogInput


type SetupOutputDo = DigitalOutput


type DeviceErrors = Literal["Field 'name' must be a string with 3 to 32 characters."]


type AreaModeErrors = Literal[
    "Field 'areaid' is mandatory and must be an integer between 1 and 6",
    "Field 'mode' is mandatory and must contain a string of one of this arrays entries: [${modeArray}]",
]


type AreaLabelErrors = Literal[
    "Field 'areaid' is mandatory and must be an integer between 1 and 6",
    "Field 'label' is mandatory and must contain a string of one of this arrays entries: [${labelArray}]",
]


type AreaTimerErrors = Literal[
    "Field 'areaid' is mandatory and must be an integer between 1 and 6",
    "Field 'timers' is mandatory.",
    "Sub field '1' of 'timers' is mandatory.",
    "Sub field '2' of 'timers' is mandatory.",
    "Sub field '3' of 'timers' is mandatory.",
    "Sub field '4' of 'timers' is mandatory.",
    "Sub field '5' of 'timers' is mandatory.",
    "Sub field 'active' of '1' of 'timers' is mandatory and must be a boolean value.",
    "Sub field 'mode' of '1' of 'timers' is mandatory and must contain a string of one of this arrays entries: [${modeArray}]",
    "Sub field 'time' of '1' of 'timers' is mandatory and must contain a string encoding a time value in 'hh:mm'",
    "Sub field 'active' of '2' of 'timers' is mandatory and must be a boolean value.",
    "Sub field 'mode' of '2' of 'timers' is mandatory and must contain a string of one of this arrays entries: [${modeArray}]",
    "Sub field 'time' of '2' of 'timers' is mandatory and must contain a string encoding a time value in 'hh:mm'",
    "Sub field 'active' of '3' of 'timers' is mandatory and must be a boolean value.",
    "Sub field 'mode' of '3' of 'timers' is mandatory and must contain a string of one of this arrays entries: [${modeArray}]",
    "Sub field 'time' of '3' of 'timers' is mandatory and must contain a string encoding a time value in 'hh:mm'",
    "Sub field 'active' of '4' of 'timers' is mandatory and must be a boolean value.",
    "Sub field 'mode' of '4' of 'timers' is mandatory and must contain a string of one of this arrays entries: [${modeArray}]",
    "Sub field 'time' of '4' of 'timers' is mandatory and must contain a string encoding a time value in 'hh:mm'",
    "Sub field 'active' of '5' of 'timers' is mandatory and must be a boolean value.",
    "Sub field 'mode' of '5' of 'timers' is mandatory and must contain a string of one of this arrays entries: [${modeArray}]",
    "Sub field 'time' of '5' of 'timers' is mandatory and must contain a string encoding a time value in 'hh:mm'",
]


type SettingsFilterErrors = Literal[
    "Field 'filter' is mandatory.",
    "Sub field 'maxRunTime' of 'filter' is mandatory and must be an integer between 90 and 270 with a step size of 10.",
    "Sub field 'reset' of 'filter' is mandatory and must be a boolean representing the command to perform a filter reset or not.",
]


type SettingsThresholdsErrors = Literal[
    "Field 'thresholds' is mandatory.",
    "Sub field 'co2' of 'thresholds' is mandatory and must be an integer between 100 and 5000 with a step size of 10.",
    "Sub field 'humidity' of 'thresholds' is mandatory and must be an integer between 10 and 95.",
]


type SettingsSleepTimeErrors = Literal[
    "Field 'sleepTime' is mandatory and must be an integer between 10 and 250"
]


type SettingsDeviceTimeErrors = Literal[
    "Field 'deviceTime' is mandatory.",
    "Sub field 'autoSynch' of 'deviceTime' is mandatory and must be a boolean value.",
    "Sub field 'date' of 'deviceTime' is mandatory and must be a ISO8601 compliant string: 'yyyy-mm-dd'.",
    "Sub field 'time' of 'deviceTime' is mandatory and must contain a string encoding a time value in 'hh:mm'",
]


type SettingsSummerModeErrors = Literal[
    "Field 'summermode' is mandatory and must be a booelan value."
]


type SetupSystemsErrors = Literal[
    "Field 'systems' is mandatory.",
    "Sub field '1' of 'systems' is mandatory.",
    "Sub field '2' of 'systems' is mandatory.",
    "Sub field '3' of 'systems' is mandatory.",
    "Sub field '4' of 'systems' is mandatory.",
    "Sub field '5' of 'systems' is mandatory.",
    "Sub field '6' of 'systems' is mandatory.",
    "Sub field 'type' of '1' of 'systems' is mandatory and must contain a string of one of this arrays entries: [${systemsArray}]",
    "Sub field 'type' of '2' of 'systems' is mandatory and must contain a string of one of this arrays entries: [${systemsArray}]",
    "Sub field 'type' of '3' of 'systems' is mandatory and must contain a string of one of this arrays entries: [${systemsArray}]",
    "Sub field 'type' of '4' of 'systems' is mandatory and must contain a string of one of this arrays entries: [${systemsArray}]",
    "Sub field 'type' of '5' of 'systems' is mandatory and must contain a string of one of this arrays entries: [${systemsArray}]",
    "Sub field 'type' of '6' of 'systems' is mandatory and must contain a string of one of this arrays entries: [${systemsArray}]",
    "Sub field 'installed' of '1' of 'systems' is mandatory and must contain a string of one of this arrays entries: [${areasArray}]",
    "Sub field 'installed' of '2' of 'systems' is mandatory and must contain a string of one of this arrays entries: [${areasArray}]",
    "Sub field 'installed' of '3' of 'systems' is mandatory and must contain a string of one of this arrays entries: [${areasArray}]",
    "Sub field 'installed' of '4' of 'systems' is mandatory and must contain a string of one of this arrays entries: [${areasArray}]",
    "Sub field 'installed' of '5' of 'systems' is mandatory and must contain a string of one of this arrays entries: [${areasArray}]",
    "Sub field 'installed' of '6' of 'systems' is mandatory and must contain a string of one of this arrays entries: [${areasArray}]",
]


type SetupAreasBoostsErrors = Literal[
    "Field 'areas' is mandatory.",
    "Sub field '1' of 'areas' is mandatory and must contain a string of one of this arrays entries: [${boostModesArray}]",
    "Sub field '2' of 'areas' is mandatory and must contain a string of one of this arrays entries: [${boostModesArray}]",
    "Sub field '3' of 'areas' is mandatory and must contain a string of one of this arrays entries: [${boostModesArray}]",
    "Sub field '4' of 'areas' is mandatory and must contain a string of one of this arrays entries: [${boostModesArray}]",
    "Sub field '5' of 'areas' is mandatory and must contain a string of one of this arrays entries: [${boostModesArray}]",
    "Sub field '6' of 'areas' is mandatory and must contain a string of one of this arrays entries: [${boostModesArray}]",
]


type SetupDigitalInputErrors = Literal[
    "Field 'digitalInput' is mandatory.",
    "Sub field 'function' of 'digitalInput' is mandatory and must contain a string of one of this arrays entries: [${diFunctionsArray}]",
    "Sub field 'areas' of 'digitalInput' is mandatory.",
    "Sub field '1' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '2' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '3' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '4' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '5' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '6' of 'areas' is mandatory and must contain a boolean value.",
]


type SetupAnalogInputErrors = Literal[
    "Field 'analogInput' is mandatory.",
    "Sub field 'function' of 'digitaanalogInputlInput' is mandatory and must contain a string of one of this arrays entries: [${aiFunctionsArray}]",
    "Sub field 'function' of 'analogInput' is mandatory and must contain a string of one of this arrays entries: [${aiFunctionsArray}]",
    "Sub field 'areas' of 'analogInput' is mandatory.",
    "Sub field '1' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '2' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '3' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '4' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '5' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '6' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field 'curveParameters' of 'analogInput' is mandatory.",
    "Sub field 'x' of 'curveParameters' is mandatory.",
    "Sub field 'yFanlevel' of 'curveParameters' is mandatory.",
    "Sub field 'yHumidity' of 'curveParameters' is mandatory.",
    "Sub field 'yCO2' of 'curveParameters' is mandatory.",
    "Sub field 'yTemp' of 'curveParameters' is mandatory.",
    "Sub field '1' of 'x' is mandatory and must contain an integer between 0 and 50.",
    "Sub field '2' of 'x' is mandatory and must contain an integer between 50 and 100.",
    "Sub field '1' of 'yFanlevel' is mandatory and must contain an integer between 0 and 3.",
    "Sub field '2' of 'yFanlevel' is mandatory and must contain an integer between 3 and 6.",
    "Sub field '1' of 'yHumidity' is mandatory and must contain an integer between 0 and 50.",
    "Sub field '2' of 'yHumidity' is mandatory and must contain an integer between 50 and 100.",
    "Sub field '1' of 'yCO2' is mandatory and must contain an integer between 0 and 1500 with a step size of 10.",
    "Sub field '2' of 'yCO2' is mandatory and must contain an integer between 1500 and 5000 with a step size of 10.",
    "Sub field '1' of 'yTemp' is mandatory and must contain an integer between -50 and 0.",
    "Sub field '2' of 'yTemp' is mandatory and must contain an integer between 0 and 50.",
]


type SetupDigitalOutputErrors = Literal[
    "Field 'digitalOuput' is mandatory.",
    "Sub field 'function' of 'digitalOuput' is mandatory and must contain a string of one of this arrays entries: [${doFunctionsArray}]",
    "Sub field 'areas' of 'digitalOuput' is mandatory.",
    "Sub field '1' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '2' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '3' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '4' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '5' of 'areas' is mandatory and must contain a boolean value.",
    "Sub field '6' of 'areas' is mandatory and must contain a boolean value.",
]


type SetupFactoryResetErrors = Literal[
    "Field 'nonce' is mandatory and must be 'I REALLY know what I do!'."
]


class Setup(TypedDict):
    systems: NotRequired[SetupSystems]
    areas: NotRequired[SetupAreas]
    inputDi: NotRequired[SetupInputDi]
    outputDo: NotRequired[SetupOutputDo]
    inputAi: NotRequired[SetupInputAi]


class Filter(TypedDict):
    maxRunTime: NotRequired[FilterMaxRunTime]


class Timer(TypedDict):
    active: NotRequired[bool]
    mode: NotRequired[AreaMode]
    time: NotRequired[str]


class AreasErrors(TypedDict):
    ModeErrors: NotRequired[AreaModeErrors]
    LabelErrors: NotRequired[AreaLabelErrors]
    TimerErrors: NotRequired[AreaTimerErrors]


class SettingsErrors(TypedDict):
    FilterErrors: NotRequired[SettingsFilterErrors]
    ThresholdsErrors: NotRequired[SettingsThresholdsErrors]
    SleepTimeErrors: NotRequired[SettingsSleepTimeErrors]
    DeviceTimeErrors: NotRequired[SettingsDeviceTimeErrors]
    SummerModeErrors: NotRequired[SettingsSummerModeErrors]


class SetupErrors(TypedDict):
    SystemsErrors: NotRequired[SetupSystemsErrors]
    AreasBoostsErrors: NotRequired[SetupAreasBoostsErrors]
    DigitalInputErrors: NotRequired[SetupDigitalInputErrors]
    AnalogInputErrors: NotRequired[SetupAnalogInputErrors]
    DigitalOutputErrors: NotRequired[SetupDigitalOutputErrors]
    FactoryResetErrors: NotRequired[SetupFactoryResetErrors]


class Error(TypedDict):
    DeviceErrors: NotRequired[DeviceErrors]
    AreasErrors: NotRequired[AreasErrors]
    SettingsErrors: NotRequired[SettingsErrors]
    SetupErrors: NotRequired[SetupErrors]


class AreaTimers(TypedDict):
    timer1: NotRequired[Timer]
    timer2: NotRequired[Timer]
    timer3: NotRequired[Timer]
    timer4: NotRequired[Timer]
    timer5: NotRequired[Timer]


class Area(TypedDict):
    label: NotRequired[AreaLabel]
    mode: NotRequired[AreaMode]
    timers: NotRequired[AreaTimers]


class Settings(TypedDict):
    filter: NotRequired[Filter]
    thresholds: NotRequired[Thresholds]
    sleepTime: NotRequired[SettingsSleepTime]
    deviceTime: NotRequired[SettingsDeviceTime]
    summermode: NotRequired[SettingsSummerMode]


class Areas(TypedDict):
    area1: NotRequired[Area]
    area2: NotRequired[Area]
    area3: NotRequired[Area]
    area4: NotRequired[Area]
    area5: NotRequired[Area]
    area6: NotRequired[Area]


class Device(TypedDict):
    id: NotRequired[str]
    name: NotRequired[DeviceName]
    users: NotRequired[Users]
    areas: NotRequired[Areas]
    telemetry: NotRequired[Telemetry]
    notifications: NotRequired[Notifications]
    controller: NotRequired[Controller]
    gateway: NotRequired[Gateway]
    settings: NotRequired[Settings]
    setup: NotRequired[Setup]
